# Generated by Django 5.2.6 on 2026-07-24 17:04

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=255)),
                ('data_nasc', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=13, unique=True)),
                ('funcao', models.CharField(choices=[('levantador', 'Levantador'), ('atacante1', 'Atacante 1 (Ponteiro)'), ('atacante2', 'Atacante 2 (Oposto)'), ('defesa', 'Defesa (Líbero)')], max_length=70)),
                ('nomec', models.CharField(max_length=150)),
                ('numeroc', models.IntegerField()),
                ('quantidadec', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('tipoc', models.CharField(choices=[('com', 'Com manga'), ('sem', 'Sem manga')], max_length=70)),
                ('tamanhoc', models.CharField(choices=[('pp', 'Tamanho PP = Dimensões: Altura 66 x Torax 46 x Quadril 46'), ('p', 'Tamanho P = Dimensões: Altura 69 x Torax 48 x Quadril 48'), ('m', 'Tamanho M = Dimensões: Altura 71 x Torax 52 x Quadril 52'), ('g', 'Tamanho G = Dimensões: Altura 73 x Torax 55 x Quadril 55'), ('gg', 'Tamanho GG = Dimensões: Altura 76 x Torax 59 x Quadril 59'), ('xg', 'Tamanho XG = Dimensões: Altura 78 x Torax 62 x Quadril 62'), ('exg', 'Tamanho EXG = Dimensões: Altura 83 x Torax 67 x Quadril 67')], default='m', max_length=400)),
                ('pagamento', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente')], default='Pendente', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=255)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em andamento'), ('finalizado', 'Finzalizado')], default='aberto', max_length=20)),
                ('placarA', models.PositiveIntegerField(default=0)),
                ('placarB', models.PositiveIntegerField(default=0)),
                ('vencedor', models.CharField(blank=True, choices=[('A', 'Time A'), ('B', 'Time B')], max_length=1, null=True)),
                ('mvp_pontos', models.PositiveIntegerField(default=0)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mvp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogos_mvp', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(blank=True, related_name='jogos_inscritos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('A', 'Time A'), ('B', 'Time B')], max_length=1)),
                ('venceu', models.CharField(choices=[('A', 'Time A'), ('B', 'Time B')], max_length=1)),
                ('pontos', models.IntegerField(default=0)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VO.registro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateField(default=django.utils.timezone.now)),
                ('jogo', models.IntegerField(blank=True, null=True)),
                ('acao', models.TextField(max_length=255)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inscricao', models.DateTimeField(default=django.utils.timezone.now)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VO.registro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
