# Generated by Django 5.2.6 on 2026-05-02 20:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(max_length=300)),
                ('telefone', models.CharField(max_length=13, unique=True)),
                ('senha', models.CharField(max_length=250)),
                ('funcao', models.CharField(choices=[('levantador', 'Levantador'), ('atacante1', 'Atacante 1 (Ponteiro)'), ('atacante2', 'Atacante 2 (Oposto)'), ('defesa', 'Defesa (Líbero)')], max_length=70)),
                ('nomec', models.CharField(max_length=150)),
                ('numeroc', models.IntegerField()),
                ('quantidadec', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')])),
                ('tipoc', models.CharField(choices=[('com', 'Com manga'), ('sem', 'Sem manga')], max_length=70)),
                ('tamanhoc', models.CharField(choices=[('pp', 'Tamanho PP = Dimensões: Altura 66 x Torax 46 x Quadril 46'), ('p', 'Tamanho P = Dimensões: Altura 69 x Torax 48 x Quadril 48'), ('m', 'Tamanho M = Dimensões: Altura 71 x Torax 52 x Quadril 52'), ('g', 'Tamanho G = Dimensões: Altura 73 x Torax 55 x Quadril 55'), ('gg', 'Tamanho GG = Dimensões: Altura 76 x Torax 59 x Quadril 59'), ('xg', 'Tamanho XG = Dimensões: Altura 78 x Torax 62 x Quadril 62'), ('exg', 'Tamanho EXG = Dimensões: Altura 83 x Torax 67 x Quadril 67')], max_length=400)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
