# Generated by Django 5.2.6 on 2026-05-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='nome',
            field=models.TextField(default='teste', max_length=255),
            preserve_default=False,
        ),
    ]
