# Generated by Django 5.2.6 on 2026-05-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VO', '0002_registro_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pagamento',
            field=models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente')], default=False, max_length=50),
        ),
    ]
