# Generated by Django 5.2.6 on 2026-05-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VO', '0003_usuario_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pagamento',
            field=models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente')], default='Pendente', max_length=50),
        ),
    ]
