# Generated by Django 5.2.6 on 2026-05-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VO', '0004_jogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogo',
            old_name='participantes',
            new_name='id_participantes',
        ),
    ]
