# Generated by Django 5.2.6 on 2026-05-10 18:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VO', '0005_rename_participantes_jogo_id_participantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='id_participantes',
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateField(default=django.utils.timezone.now)),
                ('acao', models.TextField(max_length=255)),
                ('jogo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VO.jogo')),
                ('usuario_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jogo',
            name='id_participantes',
            field=models.ManyToManyField(related_name='jogos', to=settings.AUTH_USER_MODEL),
        ),
    ]
