# Generated by Django 5.2.6 on 2026-05-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VO', '0006_remove_jogo_id_participantes_registro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogo',
            old_name='id_participantes',
            new_name='participantes',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='jogo_id',
            new_name='jogo',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
